/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import 'sst';

export {};
declare module 'sst' {
  export interface Resource {
    ApiGw2: {
      type: 'sst.aws.ApiGatewayV2';
      url: string;
    };
    AwsPermissionsTestFn: {
      name: string;
      type: 'sst.aws.Function';
    };
    EchoFn: {
      name: string;
      type: 'sst.aws.Function';
    };
  }
}
